### ISSUE TITLE
some doc convers without text

### ISSUE THREAD

**Issue by quliting** [aspose-words/Aspose.Words-for-.NET#100]
some doc convers without text .it only contains image
such as the link
https://github.com/quliting/doc.git
thank you .i waitting your reply

ps.
i want to save each page to html.

**Comment by aspose-words** [comment]
Hi,

Thanks for your inquiry. After an initial test with Aspose.Words for .NET 17.4, we were unable to reproduce this issue on our end (see [17.4-out.zip](https://github.com/aspose-words/Aspose.Words-for-.NET/files/895248/17.4-out.zip)). Please upgrade to the latest version from the following link:
[Aspose.Words for .NET 17.4](https://downloads.aspose.com/words/net)

We use the following code on our end to save each page of your test.doc to HTML.

```
Document doc = new Document(MyDir + @"test.doc");

HtmlFixedSaveOptions htmlFixedSaveOptions = new HtmlFixedSaveOptions
{
    ShowPageBorder = false,
    ExportEmbeddedFonts = true,
    ExportEmbeddedImages = true,
    ExportEmbeddedSvg = true,

    PageIndex = 0,
    PageCount = doc.PageCount
};

htmlFixedSaveOptions.PageSavingCallback = new CustomPageFileNamePageSavingCallback();

doc.Save(MyDir + @"17.4-out.html", htmlFixedSaveOptions);
```

```
private class CustomPageFileNamePageSavingCallback : IPageSavingCallback
{
    public void PageSaving(PageSavingArgs args)
    {
        // Specify name of the output file for the current page.
        args.PageFileName = string.Format(@"D:\Temp\Page_{0}.html", args.PageIndex);
    }
}
```

**Comment by quliting** [comment]
thanks for replay.i had another way to solve it out.and now i leave for that company.thank you for replay.
