### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by Prokrastinator** [aspose-words/Aspose.Words-for-.NET#103]
Aspose Words is a commercial product, isn't it? The github distribution is public. There is a MIT license. What kind of license is used for Aspose Words for Android? My employer would not spend a lot of money for a third party component. The company only has two employee. Is a rtf to html conversion using Xamarin Forms cross-platform and vice versa compatible with IOS?

**Comment by aspose-words** [comment]
Yes, all APIs of [Aspose.Words Product Family](https://www.aspose.com/products/words) are commercial and you need to buy license from Aspose to be able to use them commercially. For example, please check [Aspose.Words for Android via Xamarin pricing page](https://www.aspose.com/purchase/pricing/words/android-xamarin). Yes, you can use 'Aspose.Words for Android via Xamarin' API to convert RTF to HTML and vice versa. In case you have more queries related to License, please talk with our sales team directly by posting a thread in [Aspose.Purchase Forum](https://www.aspose.com/community/forums/aspose.purchase/220/showforum.aspx). You will be guided appropriately.

**Comment by RamblingGeekUK** [comment]
So if I wanted to use Apose.Email and give a utility away for free, would I need a license?

**Comment by aspose-words** [comment]
I am afraid, you still need to buy a License. Please talk with our sales team directly by posting a thread in [Aspose.Purchase Forum](https://forum.aspose.com/c/purchase). You will be guided appropriately.

**Comment by CodingNinjaOctocat** [comment]
Would  I need a license if my program is for personal use only?

**Comment by aspose-words** [comment]
@CodingNinjaOctocat,
I think, you still need to buy a License. Please talk with our sales team directly by posting a thread in [Aspose.Purchase Forum](https://forum.aspose.com/c/purchase). You will be guided appropriately.
