### ISSUE TITLE
Setting license in azure environment

### ISSUE THREAD

**Issue by thinkMcfly** [aspose-words/Aspose.Words-for-.NET#104]
I'd like to set the license to Aspose.Words dll, that is deployed on azure environment. The dll is being used with some USQL code behind methods. 
When setting the license in the code behind that is being called, it looks like it's being set successfully, but the resulted document (a pdf converted from word document) still has the watermark on it.
Probably the dll that was set with the license information is not the one that was actually running?
Is it possible to set the license in the scenario described above?
If it's possible, what is the proper way to do that?
If it's not possible, is there a way to "pre-license" the dll that will later be registered into azure?
thanks.

**Comment by aspose-words** [comment]
@thinkMcfly,
Please refer to the following article:
https://docs.aspose.com/display/wordsnet/Licensing

After setting the License, you can check the value of the License.IsLicensed property. It returns true if a valid license has been applied; false if the API is running in evaluation mode.
```
License license = new License();
license.SetLicense(MyDir + @"Aspose.Words.lic");
return "license.IsLicensed = " + license.IsLicensed;
```

**Comment by thinkMcfly** [comment]
thank you for your reply. 
I'm aware of the documentation link that you provided, and was working accordingly. 
The problem seems to be related to the domain of our solution:
the solution is an azure usql job, that is calling a registered assembly as code behind, which in turn uses Aspose dll. 
When we run the `SetLicense` method, it seems to be working correctly (not getting any exceptions), but than when using Aspose we still get the watermark.
We tried calling `SetLicense` both with the file name and passing a MemoryStream, both did not work.

The question is how can we set the license on azure environment and make sure we are using the same dll that was set with the license?

**Comment by aspose-words** [comment]
@thinkMcfly,

Please try using the following standalone code to see if your license still inserts an evaluation message in generated PDF?
```
License license = new License();
license.SetLicense(MyDir + @"Aspose.Total.lic");

Document doc = new Document();
DocumentBuilder builder = new DocumentBuilder(doc);

builder.Writeln("Hello World");
builder.Writeln("license.IsLicensed = " + license.IsLicensed);

doc.Save(MyDir + "18.3.pdf");
```

**Comment by aspose-words** [comment]
@thinkMcfly,

Thanks for the additional information. Can you please try [Including the License File as an Embedded Resource](https://docs.aspose.com/display/wordsnet/Licensing#Licensing-IncludingtheLicenseFileasanEmbeddedResource) and see how it goes on your end?

**Comment by romeokromeok** [comment]
@thinkMcfly did the above replies helped to resolve the issue?

**Comment by AlexNosk** [comment]
Just to make sure this issue can be closed, I tested usage of Aspose.Words in Azure Data Lake and it works fine. Here is the tested scenario. 

1.	Create an Class Library (For U-SQL Application)
![image](https://user-images.githubusercontent.com/31235892/69333719-ea456980-0c61-11ea-9486-7c2c62b6d0a7.png)
2.	Add NuGet reference to Aspose.Words 
3.	 Put some code, for testing purposes I created “Hello World” document and return it as HTML string.
```
using Aspose.Words;

namespace AsposeWordsTestUSql
{
    public class TestClass
    {
        public static string TestAW()
        {
            License lic = new License();
            lic.SetLicense("Aspose.Words.lic");
            Document doc = new Document();
            DocumentBuilder builder = new DocumentBuilder(doc);
            builder.Writeln("Hello Aspose.Words!!!");
            return doc.ToString(SaveFormat.Html);
        }
    }
}
```
4.	Add license file into your project as an embedded resource.
5.	Register your assembly in Azure Data Lake (Make sure you checked Aspose.Words in “Managed Dependencies”)
![image](https://user-images.githubusercontent.com/31235892/69334069-98e9aa00-0c62-11ea-91b2-9515f595eb01.png)
6.	Once done you can use the created method in you U-SQL job
```
USE DATABASE [TestReferenceDB];

REFERENCE ASSEMBLY AsposeWordsTestUSql;
REFERENCE ASSEMBLY [Aspose.Words];
 
@test = SELECT AsposeWordsTestUSql.TestClass.TestAW() AS html
FROM dbo.Orders;
 
OUTPUT @test TO "/output/testAW_02.csv" USING Outputters.Csv(); 
```
Note: 
•	It is required to reference both your custom assembly and Aspose.Words in your U-SQL job. 
•	Aspose.Words is enclosed into square brackets to escape dot.
Hope this will be helpful for someone. Consider the issue as resolved.
