### ISSUE TITLE
Aspose.Words with max paragraphs.

### ISSUE THREAD

**Issue by GabrielOrAnder** [aspose-words/Aspose.Words-for-.NET#107]
Hi team,

Does the Aspose.Words have a max number of readable Bookmarks by document, considering number of paragraphs or lines? I'm not using evaluate version, however, i have a document with 351 lines and 143 paragraphs and some bookmarks at the end of this document does not appear when i list them using method bellow, but, when i remove some lines/paragraphs, those bookmarks are showed.  

`foreach (Aspose.Words.Bookmark bookmark in this.Doc.Range.Bookmarks)
                {
                    if (!bookmark.Name.StartsWith("_"))
                    {
                        listaBookmarks.Add(bookmark.Name);
                    }
                }`

Best Regards!

**Comment by aspose-words** [comment]
@GabrielOrAnder ,

Have you tried the [latest version of Aspose.Words for .NET](https://www.nuget.org/packages/Aspose.Words/) i.e. **18.5**?

In case the problem still remains, please ZIP and upload the Word document you are getting this problem with to Dropbox and share the download link here for testing. We will investigate the issue further on our end and provide you more information.

**Comment by GabrielOrAnder** [comment]
Thank you to answer @aspose-words ,

I will update my version and test again, Then i told you if i had success or not.

**Comment by GabrielOrAnder** [comment]
It works! We solved the issue updating Aspose.Words and making some changes at the document.

Thank you by quickly answer.
