### ISSUE TITLE
aspose.word 在word 中操作表格如何实现换行操作

### ISSUE THREAD

**Issue by xiangxingze** [aspose-words/Aspose.Words-for-.NET#169]
在word 中操作表格如何实现换行操作？或者是移动光标的操作

**Comment by tahir-manzoor** [comment]
根据我的理解，您希望通过将光标移动到文档中的任何位置来插入换行符。 如果是这种情况，是的，您可以在文档中移动光标并使用DocumentBuilder.InsertBreak插入换行符。

DocumentBuilder有一个内部游标，您可以使用各种DocumentBuilder.MoveToXXX方法（如DocumentBuilder.MoveToDocumentStart和DocumentBuilder.MoveToField）导航到文档中的其他位置。

如果这对您没有帮助，请分享您查询的完整详细信息。 然后我会相应地回答你的问题。
