### ISSUE TITLE
aspose.words将word转换PDF时去除标记

### ISSUE THREAD

**Issue by charleszhn** [aspose-words/Aspose.Words-for-.NET#197]
![image](https://user-images.githubusercontent.com/20416202/55131528-ed7f6880-5159-11e9-9e07-825a01a5ccda.png)
在使用aspose转换时，文档保存了批注标记，请问aspose支持转换时去除这个标记吗，不更改其他格式的情况下

[null.zip](https://github.com/aspose-words/Aspose.Words-for-.NET/files/3016263/null.zip)
这是测试文件

**Comment by charleszhn** [comment]
RemovePersonalInformation()，使用了这个方法没有效果，转换后的PDF文件还是有批注信息

**Comment by awaishafeez** [comment]
@charleszhn,
您可以使用以下代码在保存为PDF之前接受或拒绝修订：

```
Document doc = new Document("E:\\null\\null.doc");
            
doc.AcceptAllRevisions();
//doc.Revisions.RejectAll();

doc.Save("E:\\null\\19.3.pdf");
```

**Comment by charleszhn** [comment]
十分感谢您，一直想着怎么移除批注信息，考虑错方向了，thank you very much！
