### ISSUE TITLE
convert word to Image is ok in some environment,but appear overlap text in another environment 

### ISSUE THREAD

**Issue by blake-cai** [aspose-words/Aspose.Words-for-.NET#202]
convert word to Image is ok in some environment,but appear overlap text in another environment 
Normal Result:
![image](https://user-images.githubusercontent.com/30404618/55861905-f0db1100-5ba9-11e9-9654-17f50f3b3820.png)
Exception Result:
![image](https://user-images.githubusercontent.com/30404618/55861944-05b7a480-5baa-11e9-9c06-09f4e83e1d27.png)

**Comment by awaishafeez** [comment]
@blake-cai,
We suggest you please [upgrade to the latest version of Aspose.Words for .NET](https://downloads.aspose.com/words/net) i.e. **19.4** and see how it goes on your end? Hope, this helps.

Please also follow [your other thread](https://forum.aspose.com/t/aspose-word-for-net-word/194818) for further proceedings.

**Comment by AlexNosk** [comment]
The issue has been moved to the forum
