### ISSUE TITLE
Unable to center image

### ISSUE THREAD

**Issue by Scomarlf** [aspose-words/Aspose.Words-for-.NET#207]
I can't make the image centered in the row,I flipped through the relevant documentation and found no solution.The effect is as follows
![1](https://user-images.githubusercontent.com/38175557/56500457-7ad99100-653d-11e9-9e79-d4be1a2d0eed.png)

**Comment by awaishafeez** [comment]
@Scomarlf, please try using the following code:

```
Shape shape = (Shape) doc.GetChildNodes(NodeType.Shape, true)[0];
shape.ParentParagraph.ParagraphFormat.Alignment = ParagraphAlignment.Center;
```

**Comment by Scomarlf** [comment]
Thinks！

**Comment by Scomarlf** [comment]
thanks
