### ISSUE TITLE
whether support add watermark to existing pdf stream?

### ISSUE THREAD

**Issue by sunweiconfidence** [aspose-words/Aspose.Words-for-.NET#239]
hi

i want to put watermark to existing pdf stream for pdf's every page, whether has method can support it? thanks

**Comment by farhan-raza** [comment]
@sunweiconfidence,

You may [Add Image Stamp in PDF File](https://docs.aspose.com/display/pdfnet/Adding+Stamp+in+a+PDF+file#AddingStampinaPDFfile-AddingImageStampinPDFFile) and feel free to contact us if you need any further assistance.

PS: I work with Aspose as Developer Evangelist.

**Comment by sunweiconfidence** [comment]
now has one question is that if the pdf or ppt file has own background image, then image stamp can't show it in pdf file after i has put image stamp to pdf file, code as below:
                            byte[] byteArrDOC = ObjectToByteArray(outputforpdf);
                            Document pdfDocumentbyteArrDOC = new Document(new MemoryStream(byteArrDOC));
                            string docWaterMarkFileDir = Server.MapPath("~/Content/Images/watermark.jpg");
                            ImageStamp imageStamp = new ImageStamp(docWaterMarkFileDir);

                            imageStamp.Background = true;
                            //set different values
                            imageStamp.Height = 100;
                            imageStamp.Width = 100; //100 in the bottom
                            imageStamp.Opacity = 0.5;

                            //imageStamp.XIndent = 100;// in the bottom 
                            //imageStamp.YIndent = 100;// in the bottom

                            // in the top
                            imageStamp.TopMargin = 10;
                            imageStamp.VerticalAlignment = VerticalAlignment.Top;
                            imageStamp.HorizontalAlignment = HorizontalAlignment.Center;

                            foreach (Page pageItem in pdfDocumentbyteArrDOC.Pages)
                            {
                                // whole page add watermark for fill with the whole screen

                                //assuming margins as zero
                                //pageItem.PageInfo.Margin.Top = 0;
                                //pageItem.PageInfo.Margin.Bottom = 0;
                                //pageItem.PageInfo.Margin.Left = 0;
                                //pageItem.PageInfo.Margin.Right = 0;
                                pageItem.AddStamp(imageStamp);
                                //for (double y = 0; y < pageItem.PageInfo.Height; y = y + imageStamp.Height)
                                //{
                                //    for (double x = 0; x < pageItem.PageInfo.Width; x = x + imageStamp.Width)
                                //    {
                                //        imageStamp.XIndent = x;
                                //        imageStamp.YIndent = y;
                                //        pageItem.AddStamp(imageStamp);
                                //    }
                                //}
                            }
                            //save generated PDF document
                            pdfDocumentbyteArrDOC.Save(outputforpdf);

**Comment by sunweiconfidence** [comment]
what method can i let my own image stamp show although pdf file has own background image? thanks

**Comment by farhan-raza** [comment]
@sunweiconfidence,

Would you please share your source file, generated file and expected output so that we may investigate further.

Moreover, please post Aspose.PDF for .NET API related issues over [respective repository](https://github.com/aspose-pdf/Aspose.PDF-for-.NET) or at Aspose Forums, for future references.

**Comment by sunweiconfidence** [comment]
code as below:
var data = FileProvider.DownloadFile(FileDownMess);
 MemoryStream fs = new MemoryStream();
MemoryStream outputforpdf = new MemoryStream();
data[0].MemoryStream.Position = 0;
 fs.Write(data[0].MemoryStream.ToArray(), 0, data[0].MemoryStream.ToArray().Length);

outputforpdf = fs;
 pdfDocumentbyteArrDOC = new Document(new MemoryStream(byteArrDOC));
                        
                            // Whether the stamp is background
                            string pdfWaterMarkFileDir = Server.MapPath("~/Content/Images/watermark.jpg");
                            imageStamp = new ImageStamp(pdfWaterMarkFileDir);
                            //imageStamp.Height = 100;
                            //imageStamp.Width = 100;
                            imageStamp.Background = true;
                            imageStamp.Opacity = 0.5;

                            foreach (Page pageItem in pdfDocumentbyteArrDOC.Pages)
                            {
                                // whole page add watermark for fill with the whole screen

                                //assuming margins as zero
                                pageItem.PageInfo.Margin.Top = 0;
                                pageItem.PageInfo.Margin.Bottom = 0;
                                pageItem.PageInfo.Margin.Left = 0;
                                pageItem.PageInfo.Margin.Right = 0;
                                
                                //work code
                                pageItem.AddStamp(imageStamp);
                            }
                            pdfDocumentbyteArrDOC.Save(outputforpdf);

  private byte[] ObjectToByteArray(Object obj)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                BinaryFormatter b = new BinaryFormatter();
                b.Serialize(ms, obj);
                return ms.ToArray();
            }
        }

this is my code, i mainly through memorystream to finish the function, hope that you can give me an advise, thanks

**Comment by farhan-raza** [comment]
@sunweiconfidence,

Thank you for sharing requested data.

We have shared our findings with you, kindly follow up in [respective thread](https://forum.aspose.com/t/whether-support-add-image-watermark-to-existing-pdf-stream/201458).

**Comment by AlexNosk** [comment]
the issue has been moved to the forum
