### ISSUE TITLE
How to implete the chart which  is a combination of two charts (Column and Line). 

### ISSUE THREAD

**Issue by ksq1063126847** [aspose-words/Aspose.Words-for-.NET#243]
1. It is feasible on  [aspose-cell ](https://github.com/aspose-cells/Aspose.Cells-for-.NET/issues/57#issue-494359173) ， how can I complete it on aspose-word，like this：

![123](https://user-images.githubusercontent.com/14009784/65031106-3aa6ff00-d973-11e9-935e-f019c1948457.png)

2. code
```
     Document doc = new Document();
     DocumentBuilder builder = new DocumentBuilder(doc);
     // Insert Column chart.
     Shape shape = builder.InsertChart(ChartType.Column, 432, 252);
     Chart chart = shape.Chart;           
     chart.Series.Add("AW Series 1", new string[] { "Category 1", "Category 2" }, new double[] { 1, 2 });

     dataDir = @"E:\\TestInsertChartColumn_out.doc";
     doc.Save(dataDir);       
```

**Comment by tahir-manzoor** [comment]
Unfortunately, Aspose.Words does not support the requested feature at the moment. However, we have logged this feature request as **WORDSNET-19242** in our issue tracking system. You will be notified once this feature is available. We apologize for your inconvenience.

**Comment by ksq1063126847** [comment]
> Unfortunately, Aspose.Words does not support the requested feature at the moment. However, we have logged this feature request as **WORDSNET-19242** in our issue tracking system. You will be notified once this feature is available. We apologize for your inconvenience.

Thanks for your replay

**Comment by kongmengfei** [comment]
Does this feature Go ON?

**Comment by AlexNosk** [comment]
@kongmengfei Unfortunately, creation of combo charts programmatically is not supported by Aspose.Words yet.
