### ISSUE TITLE
 The remote name could not be resolved: 'api.aspose.cloud' for application hosted on China region

### ISSUE THREAD

**Issue by narasappacj** [aspose-words/Aspose.Words-for-.NET#259]
I am facing API issue on application hosted on China region and for other regions, it works without any issues. 
I think [GFW](https://en.wikipedia.org/wiki/Great_Firewall) might stoping the requests. Is there any alternative API Url for https://api.aspose.cloud available for China region? 
PFB error Log

`"ExceptionMessage": "System.Net.WebException: The remote name could not be resolved: 'api.aspose.cloud'\r\n   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)\r\n   at System.Net.HttpWebRequest.GetRequestStream()\r\n   at Aspose.Words.Cloud.Sdk.ApiInvoker.PrepareRequest(String path, String method, Dictionary`2 formParams, Dictionary`2 headerParams, String body, String contentType)\r\n   at Aspose.Words.Cloud.Sdk.ApiInvoker.InvokeInternal(String path, String method, Boolean binaryResponse, String body, Dictionary`2 headerParams, Dictionary`2 formParams, String contentType)\r\n   at Aspose.Words.Cloud.Sdk.RequestHandlers.OAuthRequestHandler.RequestToken()\r\n   at Aspose.Words.Cloud.Sdk.RequestHandlers.OAuthRequestHandler.ProcessUrl(String url)\r\n   at Aspose.Words.Cloud.Sdk.ApiInvoker.<>c__DisplayClass10_0.<InvokeInternal>b__0(IRequestHandler p)\r\n`

**Comment by AlexNosk** [comment]
@narasappacj
Thank you for reporting this problem to us. As we know there are no problems with accessing Aspose.Words Cloud API from chine. One of our developer who lives in Nanjing City checked and Aspose.Words Cloud API works for him fine. In which region of Chine is your application hosted?

**Comment by narasappacj** [comment]
@AlexNosk Thanks for your reply. Only some times we are facing the above-mentioned issue. only few times issue occurs

**Comment by AlexNosk** [comment]
@narasappacj Thank you for additional information. So, can we consider this issue as resolved and close it?

**Comment by narasappacj** [comment]
@AlexNosk Before closing the ticket I would like to know how can we convert word to pdf with our Aspose API license
I tried below piece of code
` var document = new Aspose.Words.Document(@"D:\myfilename.docx");
            document.Save(@"D:\myfilenamePdf);`
How can we pass the license key for this?
 `      var configuration = new Aspose.Words.Cloud.Sdk.Configuration
            {
                ApiBaseUrl = Common.BASE_PRODUCT_URI,
                AppKey = Common.APP_KEY,
                AppSid = Common.APP_SID,
            };`

**Comment by AlexNosk** [comment]
@narasappacj
Thanks for your inquiry. Aspose.Words and Aspose.Words Cloud APIs are different products and require different licenses. See the documentation to learn [how and when to apply Aspose.Words license](https://docs.aspose.com/display/wordsnet/Licensing#Licensing-ApplyingaLicense).

If you need you can [request an evaluation license](https://purchase.aspose.com/temporary-license) to test functionality of downloadable Aspose.Words without limitations. 
IF I understand correctly, yo already have license for Aspose.Words Cloud APIs, so you can use it to convert your documents to PDF, See the documentation for [more information](https://docs.aspose.cloud/display/wordscloud/Convert+Word+Document+from+Request+Content+to+Specified+Format).

**Comment by AlexNosk** [comment]
The reported problem is not reproducible. Close the issue.
