### ISSUE TITLE
Word contains image, conversion to PDF failed

### ISSUE THREAD

**Issue by zyh1988** [aspose-words/Aspose.Words-for-.NET#286]
Word contains image, conversion to PDF failed

error message:

System.NullReferenceException:“Object reference not set to an instance of an object.”

**Comment by AlexNosk** [comment]
Could you please attach your document here for testing? We will check the issue and provide you more information.

**Comment by zyh1988** [comment]
I just tested version 18.7. I'm sorry. There is no problem testing the latest version.

**Comment by AlexNosk** [comment]
@zyh1988 Thank you for update. It is great that everything is working now. I am closing the issue.
