### ISSUE TITLE
文档横向页面加水印后页面变形，换页到下二页

### ISSUE THREAD

**Issue by 18571532202** [aspose-words/Aspose.Words-for-.NET#298]
输入文档：
[弘阳地产西南区域彭州上城项目围挡工程合同(1).docx](https://github.com/aspose-words/Aspose.Words-for-.NET/files/6179906/1.docx)
输出文档：
[弘阳地产西南区域彭州上城项目围挡工程合同_水印版.pdf](https://github.com/aspose-words/Aspose.Words-for-.NET/files/6179958/_.pdf)
实现代码：
![image](https://user-images.githubusercontent.com/35061431/111947172-de004380-8b17-11eb-892f-a38e5594948b.png)
![image](https://user-images.githubusercontent.com/35061431/111947191-e48ebb00-8b17-11eb-8eec-f5f2c34bbf40.png)
![image](https://user-images.githubusercontent.com/35061431/111947200-e9ec0580-8b17-11eb-9e6d-472c60e8a60e.png)
![image](https://user-images.githubusercontent.com/35061431/111947207-ef495000-8b17-11eb-91a7-426400e8101f.png)

**Comment by AlexNosk** [comment]
发生此问题的原因是，在您的代码中您更改了默认的段落格式，这导致文档布局的更改。 如果从文档中删除以下几行，则将保留文档的布局。

```cs
ParagraphFormat docStyle = doc.Styles.DefaultParagraphFormat.Style.ParagraphFormat;
docStyle.LineSpacingRule = LineSpacingRule.AtLeast;
docStyle.SpaceBefore = 0;
docStyle.SpaceAfter = 0;
```

我还修改了InsertWatermarkIntoHeader方法，以便它正确处理继承的页眉页脚。

```cs
private static void InsertWatermarkIntoHeader(Paragraph watermarkPara, Section sect, HeaderFooterType headerType)
{
    bool createHeaderFooter = sect.Document.FirstChild == sect;
    HeaderFooter header = sect.HeadersFooters[headerType];
    if (header == null)
    {
        if (!createHeaderFooter)
            return;

        header = new HeaderFooter(sect.Document, headerType);
        sect.HeadersFooters.Add(header);
    }
    header.AppendChild(watermarkPara.Clone(true));
}
```

**Comment by AlexNosk** [comment]
@18571532202 您是否成功获得了预期的输出？ 问题可以解决吗？
