### ISSUE TITLE
Image missing when converting a word document to pdf in linux docker container.

### ISSUE THREAD

**Issue by sunilshahi** [aspose-words/Aspose.Words-for-.NET#302]
[testfile.docx](https://github.com/aspose-words/Aspose.Words-for-.NET/files/6873187/testfile.docx)

I create a ASP.NET core 3.1 Web Application and enabled docker suppot with Linux. 

![image](https://user-images.githubusercontent.com/14316938/126883458-0f66b15e-9d98-4557-b545-ef18eb1108a7.png)

![image](https://user-images.githubusercontent.com/14316938/126883465-bb25250b-c9e8-4a9e-b61c-021ef556501f.png)

Then added nuget packages Aspose.Words 21.7.0 
And added the above attached testfile.docx to the project.

On the privacy sample razor page, I changed the OnGet Method to look like this. 

![image](https://user-images.githubusercontent.com/14316938/126883575-92218a07-d296-430b-b5a0-f92eb3a940b8.png)

I then ran the project with docker.
Then when I navigate to "/Privacy" I get a pdf download file however the images are missing. 

Orginal Docx document. 

![image](https://user-images.githubusercontent.com/14316938/126883513-4bbbe226-bd02-4461-8768-d79c0f2cb621.png)

Downloaded Pdf document 

![image](https://user-images.githubusercontent.com/14316938/126883528-3c3185bb-c9cf-49ac-9e8c-805bc5a8f179.png)

infact even Aspose watermark image is missing when I do not apply license.

**Comment by AlexNosk** [comment]
@sunilshahi Aspose.Words for .NET Standard uses SkiaSharp to deal with graphics. To make it work on Linux, you should add reference either to [SkiaSharp.NativeAssets.Linux](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux) or to [SkiaSharp.NativeAssets.Linux.NoDependencies](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies)
If you add reference to [SkiaSharp.NativeAssets.Linux](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux), you should also install `libfontconfig1` in your system. [SkiaSharp.NativeAssets.Linux](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux) depends on this library. You can use the following command to install it:
```
apt-get update && apt-get install -y libfontconfig1
```
If you do not have rights to install packages, or other reasons not to install `libfontconfig1`, you can simply use [SkiaSharp.NativeAssets.Linux.NoDependencies](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies), which does not require installation of libfontconfig1.
Please let us know if you still face any issue while using Aspose.Words.

**Comment by sunilshahi** [comment]
@AlexNosk  Thank you for your reply. 
I tried installing SkiaSharp.NativeAssets.Linux.NoDependencies that worked as expected. 

However, when I tested with SkiaSharp.NativeAssets.Linux and installing libfontconfig1 it did not work. I can use the no dependencies package and move on for now. Just wanted to let you know. 

My Dockerfile if you are interested.


`FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["TestAsposeImage/TestAsposeImage.csproj", "TestAsposeImage/"]
RUN dotnet restore "TestAsposeImage/TestAsposeImage.csproj"
COPY . .
WORKDIR "/src/TestAsposeImage"
RUN dotnet build "TestAsposeImage.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TestAsposeImage.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
RUN apt-get update
RUN apt-get install -y libfontconfig1 
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TestAsposeImage.dll"]`

**Comment by AlexNosk** [comment]
@sunilshahi Which versions of Aspose.Words and SkiaSharp.NativeAssets.Linux do you use in your project? I will check and let you know how it goes on my side.

**Comment by sunilshahi** [comment]
Here are my nuget versions from csproj.

```
  <ItemGroup>
	  <PackageReference Include="Aspose.PDF" Version="21.7.0" />
	  <PackageReference Include="Aspose.Words" Version="21.7.0" />
	  <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.14" />
	  <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.3" />
  </ItemGroup>
```

Also this is the project that I was testing with if you are interested. [Test Repo](https://github.com/sunilshahi/TestAsposeImage2)

**Comment by AlexNosk** [comment]
@sunilshahi Most likely the problem you have encountered is related to https://github.com/mono/SkiaSharp/issues/1846. I would suggest you to use SkiaSharp 2.80.1, which is used in our internal tests and shows itself as quite stable.

**Comment by joshfria** [comment]
A year later and this single issue was the only thing to save me after 6+ hours of troubleshooting. Is the need for libfontconfig1 documented anywhere?

**Comment by AlexNosk** [comment]
@joshfria I believe this is described in SkiaSharp documentation, but I cannot find this right now. Also, this is described in Aspose.Words documentation here:
<https://docs.aspose.com/words/net/how-to-run-aspose-words-in-docker/#configuring-a-dockerfile>
Implicitly this is described in SkiaSharp.NativeAssets.Linux.NoDependencies package description:
<https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies#readme-body-tab>

**Comment by sebestyn168** [comment]
Migrating web app froim windows stack to linux stack also requires [SkiaSharp.NativeAssets.Linux.NoDependencies](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies)
next step: embed used fonts in the document

**Comment by AlexNosk** [comment]
@sebestyn168 Yes, you are right. Aspose.Words for .NET Standard and .NET Core use SkiaSharp to deal with graphics, to make it work on Linux you have to add reference either to [SkiaSharp.NativeAssets.Linux](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux) or to [SkiaSharp.NativeAssets.Linux.NoDependencies](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies)

If you add reference to [SkiaSharp.NativeAssets.Linux](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux), you should also install `libfontconfig1` in your system. `SkiaSharp.NativeAssets.Linux` depends on this library. You can use the following command to install it:

```
apt-get update && apt-get install -y libfontconfig1
```
If you do not have rights to install packages, or other reasons not to install `libfontconfig1`, you can simply use [SkiaSharp.NativeAssets.Linux.NoDependencies](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies), which does not require installation of `libfontconfig1`.
