### ISSUE TITLE
aspose.words是否支持.net5?

### ISSUE THREAD

**Issue by ananadult** [aspose-words/Aspose.Words-for-.NET#306]
aspose.words是否支持.net5?

**Comment by ananadult** [comment]
nuget上最新版本的21.12.0 在.net5上安装不了

**Comment by AlexNosk** [comment]
@ananadult Aspose.Words 确实支持 .NET 5。我只是再次检查了我的身边，Aspose.Words 从 nuget 成功安装并且在 .NET 5 项目中完美运行。
您能否创建一个导致您出现问题的示例应用程序？ 我们将检查问题并为您提供更多信息。

**Comment by ananadult** [comment]
> @ananadult Aspose.Words 确实支持 .NET 5。我只是再次检查了我的身边，Aspose.Words 从 nuget 成功安装并且在 .NET 5 项目中完美运行。 您能否创建一个导致您出现问题的示例应用程序？ 我们将检查问题并为您提供更多信息。

创建.net5 桌面端应用程序，nuget安装 aspose.words 12.12.0  ，提示 NU1202: 包 System.Security.Principal.Windows 4.7.0 与 net5.0-windows7.0 (.NETCoreApp,Version=v5.0) 不兼容。 包 System.Security.Principal.Windows 4.7.0 支持: uap10.0.16299 (UAP,Version=v10.0.16299)

**Comment by AlexNosk** [comment]
@ananadult  .NET 5 实现了 .NET Standard 2.0。 Aspose.Words 从 17.12 版本开始提供 .NET Standard 2.0 dll：
https://www.nuget.org/packages/Aspose.Words/17.12.0
您使用的是旧版 12.12。 请尝试使用最新的 21.12 版本的 Aspose.Words：
https://www.nuget.org/packages/Aspose.Words/
