### ISSUE TITLE
.NET Core / .net6 support

### ISSUE THREAD

**Issue by rasmuschristensen** [aspose-words/Aspose.Words-for-.NET#307]
Hey 

Do you have a roadmap or any plans to support .net6 / .net core 3.1+  for Aspose.Words?

**Comment by AlexNosk** [comment]
@rasmuschristensen [Aspose.Words ](https://www.nuget.org/packages/Aspose.Words/)already supports .NET 6 and .NET Core 3.1. Aspose.Words provides [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) 2.0 version, which can be used in .NET Core starting from 2.0 version including .NET 5 and 6.
