### ISSUE TITLE
"error 0" after d&d of a doc

### ISSUE THREAD

**Issue by pflegende** [aspose-words/Aspose.Words-for-.NET#316]
we also attached one of the word files which failed as zip

![Opera Momentaufnahme_2022-04-25_125522_products aspose app](https://user-images.githubusercontent.com/52720420/165075711-4126ac0f-13ca-4bd1-8815-c2e72c5f3b6d.png)
[ANMELDUNG.zip](https://github.com/aspose-words/Aspose.Words-for-.NET/files/8553900/ANMELDUNG.zip)

**Comment by AlexNosk** [comment]
@pflegende I have checked your documents and cannot reproduce the problem. I can successfully merge all document as well ass different combinations of documents pairs from your archive.
