### ISSUE TITLE
aspose_word15.8.0中docx文件加多水印后，表格中行高会变大，怎么处理

### ISSUE THREAD

**Issue by xiaoxuhuicode** [aspose-words/Aspose.Words-for-.NET#320]
![Snipaste_2022-06-20_10-04-36](https://user-images.githubusercontent.com/64527312/174513572-aa4c31c7-a69f-432c-8d3f-11ea77311596.png)
![Snipaste_2022-06-20_10-05-04](https://user-images.githubusercontent.com/64527312/174513574-c6d2eb12-c731-4adf-992f-ae86342b8944.png)
![Snipaste_2022-06-20_10-05-20](https://user-images.githubusercontent.com/64527312/174513576-0410dc46-cfbd-49cc-b911-99fd57d6ec2a.png)
![Snipaste_2022-06-20_10-05-48](https://user-images.githubusercontent.com/64527312/174513577-21021e97-fb97-4c1b-9b66-4f5d036c2753.png)
![Snipaste_2022-06-20_10-12-42](https://user-images.githubusercontent.com/64527312/174513579-134f6030-af8c-49ba-b515-7cd0d2e504c0.png)
![Snipaste_2022-06-20_10-13-06](https://user-images.githubusercontent.com/64527312/174513581-71786fb0-70a6-4f2e-87ea-98cb45dc8fe3.png)

**Comment by AlexNosk** [comment]
@xiaoxuhuicode 您能否在此处附上您的真实输入和输出文档以进行测试？ 无法使用屏幕截图分析问题。
此外，如果您将代码作为代码提供，那就太好了。 使用屏幕截图分析代码并不方便。

**Comment by xiaoxuhuicode** [comment]
@AlexNosk 你好，代码是不太方便拿，只能截图

**Comment by xiaoxuhuicode** [comment]
@AlexNosk 应该不是水印问题。aspose-word15.8.0,dox文件表格行高会自动加10pt

**Comment by AlexNosk** [comment]
@xiaoxuhuicode  很遗憾，没有您的文件，我们无法分析问题。 因此，请在此处压缩并附加您的输入和有问题的输出文档以进行测试。

**Comment by xiaoxuhuicode** [comment]
@AlexNosk 我的aspose版本是15.8.0，在操作docx文件时，表格会加10pt,但是doc不会

**Comment by AlexNosk** [comment]
@xiaoxuhuicode 正如我所提到的，没有您的文件，我无法回答您的问题。 请将它们附在此处进行测试。
As I mentioned I cannot answer your question without your documents. Please attach them here for testing.

**Comment by xiaoxuhuicode** [comment]
抱歉，由于一些原因，只能借助截图方式，希望大神可以给个答复

**Comment by AlexNosk** [comment]
@xiaoxuhuicode 不幸的是，没有真实的文件是不可能分析问题的。 屏幕截图不允许了解究竟是什么导致了问题。
