### ISSUE TITLE
ASPOSE.WORD for .net    word to PDf   erro Font '阿里巴巴普惠体 R' has not been found. Using 'Courier New' font instead. Reason: font info substitution.

### ISSUE THREAD

**Issue by xiangxingze** [aspose-words/Aspose.Words-for-.NET#325]
Font '阿里巴巴普惠体 R' has not been found. Using 'Courier New' font instead. Reason: font info substitution.

**Comment by AlexNosk** [comment]
This warning means that Aspose.Words cannot find the '阿里巴巴普惠体 R' font and substitutes it with 'Courier New' font. Please see the following article to learn more about font substitution:
https://docs.aspose.com/words/net/manipulating-and-substitution-truetype-fonts/
