### ISSUE TITLE
an issues

### ISSUE THREAD

**Issue by ksleep** [aspose-words/Aspose.Words-for-.NET#338]
In the export of word content need to add an object similar to: CS ChemDraw Drawing for download After downloading Open this object by clicking on the call, what should I do

**Comment by AlexNosk** [comment]
@ksleep  It looks like you need to insert an OLE object into your document. Please see our documentation to learn how to achieve this:
<https://docs.aspose.com/words/net/working-with-ole-objects/>

PS: Please post your question in the [Aspose.Words support forum](https://forum.aspose.com/c/words/8), which is the main place for getting support.
