### ISSUE TITLE
官方提供的实例程序中没有显示百分比

### ISSUE THREAD

**Issue by skypanpan** [aspose-words/Aspose.Words-for-.NET#340]
[Test]
        public void FormatNumberOfDataLabel()
        {
            //ExStart:FormatNumberOfDataLabel
            Document doc = new Document();
            DocumentBuilder builder = new DocumentBuilder(doc);

            Shape shape = builder.InsertChart(ChartType.Column, 432, 252);

            Chart chart = shape.Chart;
            chart.Title.Text = "Data Labels With Different Number Format";

            // Delete default generated series.
            chart.Series.Clear();

            ChartSeries series1 = chart.Series.Add("Aspose Series 1", 
                new string[] { "Category 1", "Category 2", "Category 3" }, 
                new double[] { 2.5, 1.5, 3.5 });
            
            series1.HasDataLabels = true;
            series1.DataLabels.ShowValue = true;
            series1.DataLabels[0].NumberFormat.FormatCode = "\"$\"#,##0.00";
            series1.DataLabels[1].NumberFormat.FormatCode = "0.00%";
            series1.DataLabels[2].NumberFormat.FormatCode = "0.00%";
            

            // Or you can set format code to be linked to a source cell,
            // in this case NumberFormat will be reset to general and inherited from a source cell.
            series1.DataLabels[2].NumberFormat.IsLinkedToSource = true;

            doc.Save(ArtifactsDir + "WorkingWithCharts.FormatNumberOfDataLabel.docx");
            //ExEnd:FormatNumberOfDataLabel
        }
![image](https://user-images.githubusercontent.com/10138928/228561439-5fe3506b-45e8-46ff-b3e5-87bb4985bd13.png)

**Comment by AlexNosk** [comment]
@skypanpan 这是预期的输出。 在代码中，值的格式链接到第三个数据标签的来源：
```cs
series1.DataLabels[2].NumberFormat.IsLinkedToSource = true;
```
如果您需要所有标签具有相同的格式，您可以使用如下代码：
```cs
Document doc = new Document();
DocumentBuilder builder = new DocumentBuilder(doc);

Shape shape = builder.InsertChart(ChartType.Column, 432, 252);

Chart chart = shape.Chart;
chart.Title.Text = "Data Labels With Different Number Format";

// Delete default generated series.
chart.Series.Clear();

ChartSeries series1 = chart.Series.Add("Aspose Series 1",
    new string[] { "Category 1", "Category 2", "Category 3" },
    new double[] { 2.5, 1.5, 3.5 });

series1.HasDataLabels = true;
series1.DataLabels.ShowValue = true;
series1.DataLabels.NumberFormat.FormatCode = "0.00%";

doc.Save(@"C:\Temp\out.docx");
```

**Comment by skypanpan** [comment]
> @skypanpan 这是预期的输出。 在代码中，值的格式链接到第三个数据标签的来源：
> 
> ```cs
> series1.DataLabels[2].NumberFormat.IsLinkedToSource = true;
> ```
> 
> 如果您需要所有标签具有相同的格式，您可以使用如下代码：
> 
> ```cs
> Document doc = new Document();
> DocumentBuilder builder = new DocumentBuilder(doc);
> 
> Shape shape = builder.InsertChart(ChartType.Column, 432, 252);
> 
> Chart chart = shape.Chart;
> chart.Title.Text = "Data Labels With Different Number Format";
> 
> // Delete default generated series.
> chart.Series.Clear();
> 
> ChartSeries series1 = chart.Series.Add("Aspose Series 1",
>     new string[] { "Category 1", "Category 2", "Category 3" },
>     new double[] { 2.5, 1.5, 3.5 });
> 
> series1.HasDataLabels = true;
> series1.DataLabels.ShowValue = true;
> series1.DataLabels.NumberFormat.FormatCode = "0.00%";
> 
> doc.Save(@"C:\Temp\out.docx");
> ```
> 
> PS: 请注意获得支持的主要地点是 Aspose.Words 支持论坛。 请在那里发布您的问题。 https://forum.aspose.com/c/words/8



> @skypanpan 这是预期的输出。 在代码中，值的格式链接到第三个数据标签的来源：
> 
> ```cs
> series1.DataLabels[2].NumberFormat.IsLinkedToSource = true;
> ```
> 
> 如果您需要所有标签具有相同的格式，您可以使用如下代码：
> 
> ```cs
> Document doc = new Document();
> DocumentBuilder builder = new DocumentBuilder(doc);
> 
> Shape shape = builder.InsertChart(ChartType.Column, 432, 252);
> 
> Chart chart = shape.Chart;
> chart.Title.Text = "Data Labels With Different Number Format";
> 
> // Delete default generated series.
> chart.Series.Clear();
> 
> ChartSeries series1 = chart.Series.Add("Aspose Series 1",
>     new string[] { "Category 1", "Category 2", "Category 3" },
>     new double[] { 2.5, 1.5, 3.5 });
> 
> series1.HasDataLabels = true;
> series1.DataLabels.ShowValue = true;
> series1.DataLabels.NumberFormat.FormatCode = "0.00%";
> 
> doc.Save(@"C:\Temp\out.docx");
> ```
> 
> PS: 请注意获得支持的主要地点是 Aspose.Words 支持论坛。 请在那里发布您的问题。 https://forum.aspose.com/c/words/8

thanks a lot!  I will go to this forum in the future https://forum.aspose.com/c/words/8
