### ISSUE TITLE
hello,Aspose.Word中 builder.insertChart()方式怎么生成带折现的柱状图呢?

### ISSUE THREAD

**Issue by skypanpan** [aspose-words/Aspose.Words-for-.NET#341]

**Comment by AlexNosk** [comment]
@skypanpan  您能否更详细地阐述您的要求？ 请在 MS Word 中创建预期的输出文档并将其附在此处以供我们参考。 我们将对其进行检查并为您提供更多信息。

PS: 请注意获得支持的主要地点是 Aspose.Words 支持论坛。 请在那里发布您的问题。
<https://forum.aspose.com/c/words/8>

**Comment by skypanpan** [comment]
> @skypanpan 您能否更详细地阐述您的要求？ 请在 MS Word 中创建预期的输出文档并将其附在此处以供我们参考。 我们将对其进行检查并为您提供更多信息。
> 
> PS: 请注意获得支持的主要地点是 Aspose.Words 支持论坛。 请在那里发布您的问题。 https://forum.aspose.com/c/words/8

thanks a lot!  I will go to this forum in the future https://forum.aspose.com/c/words/8
