### ISSUE TITLE
Convert text to PNG in C# for Unity

### ISSUE THREAD

**Issue by aadi3124** [aspose-words/Aspose.Words-for-.NET#349]
Hi,
I want to use this feature "Convert text to PNG in C#" in my unity project. Can you please suggest a way "how to use" this in Unity. What dependencies and plugins do I need to integrate this in my Unity project. What are the steps gonna be. Please help. I have been stuck for a week to achieve this.

I have the package installed still getting the error:
error CS0246: The type or namespace name 'Aspose' could not be found (are you missing a using directive or an assembly reference?)

<img width="1018" alt="Screenshot 2023-06-30 at 12 50 15 PM" src="https://github.com/aspose-words/Aspose.Words-for-.NET/assets/22842993/6d893473-633a-4e99-a84e-a8fa2bb6085e">

Thanks in advance.

**Comment by AlexNosk** [comment]
@aadi3124 The question is already answered in Aspose.Words support forum:
<https://forum.aspose.com/t/rendering-text-to-png-via-aspose-words-api-in-unity-project/267540/4>
Let's continue the discussion there, since forum is the main place for getting support.
