### ISSUE TITLE
Docx to markdown conversion issues

### ISSUE THREAD

**Issue by xhnbzdl** [aspose-words/Aspose.Words-for-.NET#356]
When converting docx to markdown the H1 tags become bold (**content**) and there are also blocks of code that don't convert properly
![image](https://github.com/aspose-words/Aspose.Words-for-.NET/assets/84184815/fabf4210-ab00-404c-ac54-a062ef5898aa)

**Comment by AlexNosk** [comment]
@xhnbzdl Could you please attach your input, output and expected output documents here for testing? We will check the issue and provide you more information.

**Comment by xhnbzdl** [comment]
The input word document is shown below:
![image](https://github.com/aspose-words/Aspose.Words-for-.NET/assets/84184815/aaceeedb-ca46-4f24-bb6b-fa485a7c87f6)
Since github can't upload attachments, the specific documentation file has been sent to you via email。
The expected output markdown is as follows:
 
![image](https://github.com/aspose-words/Aspose.Words-for-.NET/assets/84184815/eac70941-f19f-41e7-9787-e9449d90df0c)

The actual output markdown is as follows:
 
![image](https://github.com/aspose-words/Aspose.Words-for-.NET/assets/84184815/f354821f-ec01-42ce-8cbd-01d02d9e5675)

**Comment by xhnbzdl** [comment]
Enter the word data of the document in the attachment。
The expected output markdown is as follows:

The actual output markdown is as follows:

从 Windows 版邮件发送

发件人: AlexNosk
发送时间: 2023年10月17日 13:05
收件人: aspose-words/Aspose.Words-for-.NET
抄送: xhnbzdl; Mention
主题: Re: [aspose-words/Aspose.Words-for-.NET] Docx to markdown conversionissues (Issue #356)

@xhnbzdl Could you please attach your input, output and expected output documents here for testing? We will check the issue and provide you more information.

**Comment by xhnbzdl** [comment]
I don't seem to be able to send you my test files via github or email!

**Comment by AlexNosk** [comment]
@xhnbzdl Unfortunately, screenshots does not allow to analyze the issue. You can zip and attach your file here or report the issue in [Aspose.Words support forum,](https://forum.aspose.com/c/words/8) which is the main place for support and attach the documents there.

**Comment by xhnbzdl** [comment]
> @xhnbzdl Unfortunately, screenshots does not allow to analyze the issue. You can zip and attach your file here or report the issue in [Aspose.Words support forum,](https://forum.aspose.com/c/words/8) which is the main place for support and attach the documents there.

ok
